name: "Publish Dotnet Newrelic-Instrumentation for Windows"

on:
  push:
    paths:
      - 'src/apm/dotnet_windows/**'
      - '.github/workflows/publish-newrelic-instrumentation-dotnet-windows.yml'
    branches:
      - main
  pull_request:
    paths:
      - 'src/apm/dotnet_windows/**'
      - '.github/workflows/publish-newrelic-instrumentation-dotnet-windows.yml'
  workflow_dispatch:

jobs:
  publish:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Read version
        id: version
        run: echo "VERSION=$(cat src/apm/dotnet_windows/version.txt)" >> $GITHUB_ENV

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository_owner }}/k8s-agents-operator-windows/newrelic-dotnet-windows-init
          tags: |
            type=match,pattern=v(.*),group=1,value=v${{ env.VERSION }}

      - name: Login to GitHub Package Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PERSONAL_PUSH_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/k8s-agents-operator-windows/newrelic-dotnet-windows-init:${{ env.VERSION }} \
            -f src/apm/dotnet_windows/Dockerfile .

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/k8s-agents-operator-windows/newrelic-dotnet-windows-init:${{ env.VERSION }}
